services:
  authmcsv:
    build:
      context: ./auth-microservice
    ports:
      - "8001:8001"

  productsmcsv:
    build:
      context: ./product-microservice
    ports:
      - "8002:8002"

  notificationsmcsv:
    build:
      context: ./notifications-microservice
    ports:
      - "8005:8005"

  gatewaymcsv:
    build:
      context: ./gateway-microservice
    ports:
      - "8888:8888"
    depends_on:
      - authmcsv
      - notificationsmcsv
