
# GQL Query to get a notification by id
query {
  getNotificationById(id:"6619f4c3a370e60239ff81fb"){
    userId
    message
    isRead
  }
}


# GET all products
query {
  getProducts() {
    id
    createdAt
    updatedAt
    deletedAt
    userID
    state
    status
    name
    description
    image
    category
    price
    rate
    ubication
  }
}

# GET all comments
query {
  getComments() {
    id
    createdAt
    updatedAt
    deletedAt
    userID
    productID
    comment
    rating
  }
}


# GQL Mutation to create a notification
mutation {
  createNotification(userId:"123", title:"New Notification 111", message:"This is a new notification", isRead:false){
    message
    isRead
  }
}

