### Create Notification
POST http://localhost:8005/notifications
Content-Type: application/json

{
    "userId": "123",
    "title": "Notification Title 1",
    "message": "Notification Message",
    "type": "info",
    "isRead": false
}


### Get Notification By Id
GET  http://localhost:8005/notifications/id/6614ae0c6a0447ad87d2a614

### Get Notification By Id
GET http://localhost:8005/notifications/id/6614ae3d6a0447ad87d2a618



### Get Notifications By User Id
GET  http://localhost:8005/notifications/userId/123

### Get Notifications By User Id
GET http://localhost:8005/notifications/userId/223


### Mark Notification As Read
PUT http://localhost:8005/notifications/markAsRead/6614ae346a0447ad87d2a617

### Mark All Notifications As Read
PUT http://localhost:8005/notifications/markAllAsRead/223