### Create Notification
POST http://localhost:8005/notifications
Content-Type: application/json

{
    "userId": "223",
    "title": "Notification Title 4",
    "message": "Notification Message",
    "type": "info",
    "isRead": false
}


### Get Notification By Id
GET  http://localhost:8005/notifications/661771e09829d873e2925f1b

### Get Notification By Id
GET http://localhost:8005/notifications/6614ae3d6a0447ad87d2a618



### Get Notifications By User Id
GET  http://localhost:8005/notifications/user/123

### Get Notifications By User Id
GET http://localhost:8005/notifications/user/223


### Mark Notification As Read
PUT http://localhost:8005/notifications/markAsRead/6614ae346a0447ad87d2a617

### Mark All Notifications As Read
PUT http://localhost:8005/notifications/markAllAsRead/223