// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type Notification struct {
	ID      string `json:"_id"`
	UserID  string `json:"userId"`
	Message string `json:"message"`
	IsRead  bool   `json:"isRead"`
}

type NotificationInput struct {
	UserID  string `json:"userId"`
	Title   string `json:"title"`
	Message string `json:"message"`
	IsRead  bool   `json:"isRead"`
}

type NotificationResponse struct {
	Message string `json:"message"`
	IsRead  bool   `json:"isRead"`
}

type Query struct {
}
