// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type Notification struct {
	ID        string  `json:"id"`
	UserID    *string `json:"userId,omitempty"`
	Title     *string `json:"title,omitempty"`
	Message   *string `json:"message,omitempty"`
	Image     *string `json:"image,omitempty"`
	IsRead    *bool   `json:"isRead,omitempty"`
	Type      *string `json:"type,omitempty"`
	CreatedAt *string `json:"createdAt,omitempty"`
	UpdatedAt *string `json:"updatedAt,omitempty"`
}

type Query struct {
}

type User struct {
	IDAuth    *string `json:"idAuth,omitempty"`
	Email     *string `json:"email,omitempty"`
	Role      *string `json:"role,omitempty"`
	Name      *string `json:"name,omitempty"`
	Image     *string `json:"image,omitempty"`
	Ubication *string `json:"ubication,omitempty"`
	Password  *string `json:"password,omitempty"`
}
